
[functions.send-order-ready-email]
enabled = true
verify_jwt = true
import_map = "./functions/send-order-ready-email/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-order-ready-email/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-order-ready-email/*.html" ]

[functions.send-order-cancelled-email]
enabled = true
verify_jwt = true
import_map = "./functions/send-order-cancelled-email/deno.json"
entrypoint = "./functions/send-order-cancelled-email/index.ts"

[functions.handle-contact-message]
enabled = true
verify_jwt = false
import_map = "./functions/handle-contact-message/deno.json"
entrypoint = "./functions/handle-contact-message/index.ts"

[functions.send-admin-push]
enabled = true
verify_jwt = true
import_map = "./functions/send-admin-push/deno.json"
entrypoint = "./functions/send-admin-push/index.ts"

[functions.send-client-push]
enabled = true
verify_jwt = true
import_map = "./functions/send-client-push/deno.json"
entrypoint = "./functions/send-client-push/index.ts"

[functions.send-broadcast-announcement]
enabled = true
verify_jwt = true
import_map = "./functions/send-broadcast-announcement/deno.json"
entrypoint = "./functions/send-broadcast-announcement/index.ts"

[functions.send-daily-payment-summary-email]
enabled = true
verify_jwt = false
import_map = "./functions/send-daily-payment-summary-email/deno.json"
entrypoint = "./functions/send-daily-payment-summary-email/index.ts"

[functions.send-egg-order-reminders]
enabled = true
verify_jwt = false
import_map = "./functions/send-egg-order-reminders/deno.json"
entrypoint = "./functions/send-egg-order-reminders/index.ts"
